### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by euwyn** [jlyman/react-native-rating-requestor#1]
Nice, would be great to see Android support!

**Comment by koppelaar** [comment]
+1

**Comment by jlyman** [comment]
I agree! Would either one of you @euwyn or @koppelaar be able to pull down the `android-support` branch and test it out on an physical device? I currently don't have access to one, so my testing is limited to the emulator (and therefore I can't test the Play Store link).

I added an `npm run example-android` script to the package that copies the dev version of the package into the example app for easy running.

**Comment by jlyman** [comment]
Should be available now as of version 2.0.0.
