### ISSUE TITLE
iOS vs Android button ordering

### ISSUE THREAD

**Issue by farazs** [jlyman/react-native-rating-requestor#13]
The code uses button ordering for Android ie. [bottom, middle, top]. On iOS the button ordering for alert is [top, middle, bottom] so the `accept` button is at the bottom which doesn't make much sense from a UX point of view. You want the desirable button to be at the top and the least desirable at the bottom.

There should be a platform check to reverse the order of buttons based on iOS vs Android.

**Comment by yihanseattle** [comment]
https://github.com/jlyman/react-native-rating-requestor/pull/14

**Comment by yihanseattle** [comment]
#14
