### ISSUE TITLE
Swap to using SKStore​Review​Controller on iOS

### ISSUE THREAD

**Issue by jlyman** [jlyman/react-native-rating-requestor#17]
Apple is mandating all apps to drop custom rating dialogs in iOS 11 and use `SKStore​Review​Controller`, so we'll need to switch to using that on iOS. This would be a net positive anyway (though slightly less flexible than what's already in place).

**Comment by kesha-antonov** [comment]
https://github.com/jlyman/react-native-rating-requestor/pull/16

**Comment by jlyman** [comment]
Should be resolved by #16.
