### ISSUE TITLE
No longer maintained?

### ISSUE THREAD

**Issue by rpastorelle** [jlyman/react-native-rating-requestor#19]
Since this doesn't seem to be maintained anymore — Is anyone using a reliable fork of this? I am thinking of using this one: 
> https://github.com/rizzomichaelg/react-native-rating-requestor/

**Comment by joncursi** [comment]
@rpastorelle I've been using the above fork with great success. It has the added benefit of native reviews for iOS > 10.3, which this repo currently doesn't support.

**Comment by kesha-antonov** [comment]
+ Relying on this repo

**Comment by jlyman** [comment]
It's maintained... verrrry slowly. ;)

For those needing the native iOS SKStoreReviewController I'd suggest using @rizzomichaelg's fork for now until I can implement it. In the meantime, I've updated a few other things in the original repo to support things like button ordering changes.

Thanks for the patience and alternative forks everyone, it's open source after all.
