### ISSUE TITLE
Android broken link

### ISSUE THREAD

**Issue by eyeCU113** [jlyman/react-native-rating-requestor#27]
It works fine on IOS, but on android I get an error when I try to rate the app:
"To view this content install and set up a web browsing app".

I guess it has something to do with:
https://www.reddit.com/r/Android/comments/7lv04m/google_play_now_intercepts_all_links_to_the/

**Comment by eyeCU113** [comment]
Ok, the reason I was getting this ridiculous error was because in app.android.js the wrong appID was set up. It was using the apple ID (which is a number), instead of the google ID (which is the name of the package, ex. 'com.my.app').

**Comment by jlyman** [comment]
Ah okay, glad you got it figured out. I had started looking into it but wasn't making headway as it seemed odd. Good stuff!
