### ISSUE TITLE
does not work? [ios]

### ISSUE THREAD

**Issue by Richi2293** [jlyman/react-native-rating-requestor#32]
Hi,

I'm trying this component on ios and it does not seem to work.

When I click on "Sure!" In the popup, Safari opens but gives me an error:

![image](https://user-images.githubusercontent.com/5848941/42264804-ff60e2dc-7f71-11e8-9cec-5a1393fbe6cf.png)

is not the repo updated?

Thanks

**Comment by jlyman** [comment]
@Richi2293 looks like this isn't an issue for you anymore, but for anyone else curious about the same thing, when running this in the simulator this is what you'll get, since you can't open the App Store on the simulator.
