### ISSUE TITLE
timingFunction is not working?

### ISSUE THREAD

**Issue by lohkaeo** [jlyman/react-native-rating-requestor#41]
Hello,

I try to call timingFunction, but it's not working. Please see code below.

import RatingRequestor from "react-native-rating-requestor";

const RatingTracker = new RatingRequestor(
  Platform.select({
    ios: 'xxxxxxxxx',
    android: 'app.xxx',
  }), {
  shouldBoldLastButton: true,
  timingFunction: function(currentCount) {
    return currentCount > 1 && Math.log(currentCount) / Math.log(3) % 1 == 0;
  }
});

**Comment by jlyman** [comment]
When you say that it isn't working, can you give a little more detail? Is the popup just never firing? Does it do something weird?

**Comment by jlyman** [comment]
Closing needing more info for now, but feel free to reopen if needed.
