### ISSUE TITLE
react-native-store-review 0.1.5 → 0.2.0

### ISSUE THREAD

**Issue by allenmanning** [jlyman/react-native-rating-requestor#47]
When I try and update `react-native-store-review 0.1.5 → 0.2.0` I get:

      Could not resolve dependency:
            npm ERR! peer react-native-store-review@"^0.1.5" from react-native-rating-requestor@4.2.0

It seems a peer version update is required.

**Comment by jlyman** [comment]
You're right @allenmanning, looks like 0.2.0 won't satisfy the semver requirement of `^0.1.5`, that's the fun of pre-1.0 versions. :) 

Thanks for the catch. Any chance you'd be willing to bump the dependency and submit a PR?
