### ISSUE TITLE
Will not work in IOS due to peerDependency change

### ISSUE THREAD

**Issue by jforaker** [jlyman/react-native-rating-requestor#66]
There is a peerDependency for https://github.com/oblador/react-native-store-review set to 

```
"react-native-store-review": "^0.1.5"
```

But in the latest version, that library has deprecated an all important method used by the current version of this library, called `StoreReview.isAvailable` 

```
if (Platform.OS === 'ios' && StoreReview.isAvailable) {
   StoreReview.requestReview();
}
```

In [0.3.0 they removed the method](https://github.com/oblador/react-native-store-review/releases/tag/v0.3.0): 
> BREAKING CHANGE: Drop support for Android <21 & iOS < 12.4, and remove isAvailable constant.

So `StoreReview.isAvailable` will return undefined, and that "if" statement will never succeed. Therefore, this never gets called:

```
StoreReview.requestReview();
```

For me, the fix was to do a patch and remove the call to `isAvailable`:

```
diff --git a/node_modules/react-native-rating-requestor/index.js b/node_modules/react-native-rating-requestor/index.js
index 7f87cc3..3dfded5 100644
--- a/node_modules/react-native-rating-requestor/index.js
+++ b/node_modules/react-native-rating-requestor/index.js
@@ -121,7 +121,7 @@ export default class RatingRequestor {
           RatingsData.recordRated();
           callback(true, "accept");
           // This API is only available on iOS 10.3 or later
-					if (Platform.OS === 'ios' && StoreReview.isAvailable) {
+					if (Platform.OS === 'ios') {
 						StoreReview.requestReview();
 					} else {
 						Linking.openURL(this.storeUrl);
```

**Comment by jlyman** [comment]
Thank you so much for the investigation and fix @jforaker! Pushed a new version out with this suggested diff (v4.3.0).
