### ISSUE TITLE
RatingRequestor is not a constructor

### ISSUE THREAD

**Issue by tomtang539** [jlyman/react-native-rating-requestor#7]
Hi,
I'm getting an error when I try to initialize RatingRequestor.  I'm putting the following code in my index.ios.js

```
import RatingRequestor from 'react-native-rating-requestor'
let RatingTracker = new RatingRequestor('[my app id]')
```

And I get the following error when trying to run my app:
`
RatingRequestor is not a constructor
`

Any help is greatly appreciated.  Thanks!

**Comment by jlyman** [comment]
Hmm that's odd. If you log out `RatingRequestor` before trying to instantiate it, what do you get? Seems otherwise like it's following the same pattern as [in the example app](https://github.com/jlyman/react-native-rating-requestor/blob/master/examples/RatingRequestorExample/index.ios.js).

**Comment by jlyman** [comment]
@tomtang539 did you ever get this to work or should I close?
